#!/usr/bin/env python3
"""Build site/data.js from the processed image files.

Groups files by leading number (piece), picks the clean image as
primary and any -framed image as secondary, and derives a display
name from the filename slug. Size and price are the same for every
piece and are stated once in the site's order-info banner rather than
per piece, so they aren't included here.
"""
import glob
import os
import re
import json
from PIL import Image, ImageStat

IMG_DIR = "docs/assets/img/full"
THUMB_DIR = "docs/assets/img/thumb"
OUT_FILE = "docs/data.js"

SMALL_WORDS = {"on", "and", "with", "the", "of", "in", "a", "an", "at", "for"}

# Fraction of the thumbnail's height (from the bottom) that the card
# label overlay actually covers — matches the gallery card CSS.
LABEL_ZONE_FRACTION = 0.28
# Average luminance (0-255) of that zone below which we treat the area
# as dark and use light text; at or above it we use dark text instead.
LUMINANCE_THRESHOLD = 140


def slug_to_title(slug):
    words = slug.split("-")
    out = []
    for i, w in enumerate(words):
        if i > 0 and w in SMALL_WORDS:
            out.append(w)
        else:
            out.append(w.capitalize())
    return " ".join(out)


def label_theme_for(thumb_path):
    """Sample the bottom strip of a thumbnail (where the card label sits)
    and decide whether light or dark label text will read better on it."""
    im = Image.open(thumb_path).convert("L")
    w, h = im.size
    top = max(0, round(h * (1 - LABEL_ZONE_FRACTION)))
    zone = im.crop((0, top, w, h))
    avg_luminance = ImageStat.Stat(zone).mean[0]
    return "dark" if avg_luminance < LUMINANCE_THRESHOLD else "light"


def main():
    files = sorted(os.path.basename(f) for f in glob.glob(os.path.join(IMG_DIR, "*.jpg")))

    pieces = {}
    for fname in files:
        stem = os.path.splitext(fname)[0]
        m = re.match(r"^(\d+)-(.+)$", stem)
        number, slug = m.group(1), m.group(2)
        is_framed = slug.endswith("-framed")
        base_slug = slug[: -len("-framed")] if is_framed else slug

        piece = pieces.setdefault(number, {
            "number": number,
            "name": slug_to_title(base_slug),
            "slug": base_slug,
            "clean": None,
            "framed": None,
        })
        if is_framed:
            piece["framed"] = fname
        else:
            piece["clean"] = fname
            piece["name"] = slug_to_title(base_slug)

    ordered = [pieces[k] for k in sorted(pieces.keys(), key=int)]

    for p in ordered:
        thumb_path = os.path.join(THUMB_DIR, p["clean"])
        p["labelTheme"] = label_theme_for(thumb_path)

    with open(OUT_FILE, "w") as f:
        f.write("// Auto-generated by scripts/generate_data.py — do not hand-edit image filenames here.\n")
        f.write("// Update the piece 'name' field as needed.\n")
        f.write("const PIECES = ")
        f.write(json.dumps(ordered, indent=2))
        f.write(";\n")

    print(f"Wrote {len(ordered)} pieces to {OUT_FILE}")
    for p in ordered:
        pair = " + framed" if p["framed"] else ""
        print(f"  {p['number']:>2}  {p['name']:35} {p['labelTheme']:5} {pair}")


if __name__ == "__main__":
    main()
