#!/usr/bin/env python3
"""Build site/data.js from the processed image files.

Groups files by leading number (piece), picks the clean image as
primary and any -framed image as secondary, and derives a display
name from the filename slug. Size and price are left as placeholders
for the artist to fill in later.
"""
import glob
import os
import re
import json

IMG_DIR = "docs/assets/img/full"
OUT_FILE = "docs/data.js"

SMALL_WORDS = {"on", "and", "with", "the", "of", "in", "a", "an", "at", "for"}


def slug_to_title(slug):
    words = slug.split("-")
    out = []
    for i, w in enumerate(words):
        if i > 0 and w in SMALL_WORDS:
            out.append(w)
        else:
            out.append(w.capitalize())
    return " ".join(out)


def main():
    files = sorted(os.path.basename(f) for f in glob.glob(os.path.join(IMG_DIR, "*.jpg")))

    pieces = {}
    for fname in files:
        stem = os.path.splitext(fname)[0]
        m = re.match(r"^(\d+)-(.+)$", stem)
        number, slug = m.group(1), m.group(2)
        is_framed = slug.endswith("-framed")
        base_slug = slug[: -len("-framed")] if is_framed else slug

        piece = pieces.setdefault(number, {
            "number": number,
            "name": slug_to_title(base_slug),
            "slug": base_slug,
            "clean": None,
            "framed": None,
            "size": "Size: TBD",
            "price": "Price: TBD",
        })
        if is_framed:
            piece["framed"] = fname
        else:
            piece["clean"] = fname
            piece["name"] = slug_to_title(base_slug)

    ordered = [pieces[k] for k in sorted(pieces.keys(), key=int)]

    with open(OUT_FILE, "w") as f:
        f.write("// Auto-generated by scripts/generate_data.py — do not hand-edit image filenames here.\n")
        f.write("// Update the piece 'name', 'size', and 'price' fields as needed.\n")
        f.write("const PIECES = ")
        f.write(json.dumps(ordered, indent=2))
        f.write(";\n")

    print(f"Wrote {len(ordered)} pieces to {OUT_FILE}")
    for p in ordered:
        pair = " + framed" if p["framed"] else ""
        print(f"  {p['number']:>2}  {p['name']:35} {pair}")


if __name__ == "__main__":
    main()
